import type { Entity, SourceManifest } from "./validation";

export const sourceManifests: SourceManifest[] = [
  {
    id: "ordem2.playtest-alpha.agentes",
    title: "Ordem Paranormal RPG 2 - Playtest Alpha - Agentes",
    version: "alpha",
    type: "core-playtest",
    filename: "Ordem Paranormal RPG 2 - Playtest Alpha - Agentes.pdf",
    sha256: "",
    imported_at: "",
    language: "pt-BR",
    status: "available",
    notes: "",
    source_origin: "user-provided",
    publication_date: "",
    supersedes: "",
    superseded_by: "",
  },
  {
    id: "ordem2.playtest-alpha.ato-i-extras",
    title: "Ordem Paranormal RPG 2 - Playtest Alpha - Ato I - Extras",
    version: "alpha",
    type: "extras",
    filename: "Ordem Paranormal RPG 2 - Playtest Alpha - Ato I - Extras.pdf",
    sha256: "",
    imported_at: "",
    language: "pt-BR",
    status: "available",
    notes: "",
    source_origin: "user-provided",
    publication_date: "",
    supersedes: "",
    superseded_by: "",
  },
  {
    id: "ordem2.playtest-alpha.ato-ii-extras",
    title: "Ordem Paranormal RPG 2 - Playtest Alpha - Ato II - Extras",
    version: "alpha",
    type: "extras",
    filename: "Ordem Paranormal RPG 2 - Playtest Alpha - Ato II - Extras.pdf",
    sha256: "",
    imported_at: "",
    language: "pt-BR",
    status: "available",
    notes: "",
    source_origin: "user-provided",
    publication_date: "",
    supersedes: "",
    superseded_by: "",
  },
];

export const entities: Entity[] = [
  {
    id: "creature.mock.example",
    type: "creature",
    name: "Mock Creature",
    aliases: ["Mock Specimen"],
    summary: "Entidade experimental para validação de fluxo.",
    description: "Registro sintético não oficial para testes de estrutura.",
    version: "alpha",
    sourceIds: ["ordem2.playtest-alpha.agentes"],
    tags: ["type/creature", "version/alpha", "status/experimental"],
    relationships: [
      {
        id: "rel.mock.uses.rule",
        sourceEntityId: "creature.mock.example",
        targetEntityId: "rule.mock.example",
        type: "USES",
        sourceDocumentId: "ordem2.playtest-alpha.agentes",
        sourcePage: 0,
        sourceSection: "mock",
        version: "alpha",
        confidence: "suggested",
        notes: "experimental",
      },
    ],
    mechanics: { damageType: "unknown" },
    stats: { hp: "unknown" },
    contentStatus: "experimental",
    verificationStatus: "UNVERIFIED",
    provenance: [
      {
        documentId: "ordem2.playtest-alpha.agentes",
        page: 0,
        section: "mock",
        method: "manual",
        confidence: "unknown",
        verified: false,
        notes: "Conteúdo experimental.",
      },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "rule.mock.example",
    type: "rule",
    name: "Mock Rule",
    version: "alpha",
    sourceIds: ["ordem2.playtest-alpha.agentes"],
    tags: ["type/rule", "version/alpha", "status/experimental"],
    relationships: [],
    contentStatus: "experimental",
    verificationStatus: "UNVERIFIED",
    provenance: [
      {
        documentId: "ordem2.playtest-alpha.agentes",
        page: 0,
        method: "manual",
        confidence: "unknown",
        verified: false,
        notes: "Conteúdo experimental.",
      },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];
